### ISSUE TITLE
Multiple bugs/inconsistencies + so-so UX

### ISSUE THREAD

**Issue by desmap** [accounts-js/accounts#930] opened 2020-04-04 08:34 UTC
This is not just one bug reports but multiple. It's for others driving by and a note for myself to get a quick overview and about if I should to use accounts in the first place.

Accounts' idea is great because nobody likes to do this over and over, so my requirements are turn-key-ready or at least less work than doing it myself, intuitive, easy to integrate with existing graphql structures, a well maintained repo paired with responsive/constructive maintainers.

- [minor] Docs inconsistent (GH README vs site), eg. Getting Started section `merge` vs graphql-tools helpers
- [minor] GH README buggy code, eg. `mergeGraphQLModules` not declared (guess it should have been ...Schema)
- [minor] GH README examples lack setting up the db
- [minor] Mongo docs example lacks second arg for `new AccountsServer` (TS says `services`)
- [major] despite having an own db connection to Mongo with `useUnifiedTopology: true`, Mongo complains that it's not there and Mongo reports about a failed connect => why does accounts tries to connect itself to Mongo? And if, it's ok but then it should do it in a proper way, hint: useUnifiedTopology (this has some aftertaste on the repo, Mongo introduced this this ages go), and it should be stated somewhere in the docs what accounts is doing
- [minor but infuriating] Docs actually don't tell how to let use your Mongo connection; setting up Mongo is described in the respective chapter but nowhere how to get the stuff into the server
- [minor but infuriating] Docs state that @apollo/boost is for the standalone server but then it's imported in the existing-server example; guess there must be a reason but for the reader it's just another question mark
- [ux/general/major] setup and API is very granular/scattered, good bc modular and probably flexible (I assume that's actually not flexible because of lacking Apollo Fed support) but also tedious bc there are many modules to be imported and most of the time I am in the docs trying to follow some guide but not actual thinking myself what to do
- [ux/general] better than any legacy solution such as passport because the structure makes sense (on paper)
- [ux/general/major] when merging with an existing scheme, would't Apollo Federation be the right choice? Apollo Fed provides a tighter integration with your existing scheme than just a simple merge _=> my first impression was here that accounts is such a modular API thriving for flexibility but the actual core isn't flexible, so I end up with a low abstraction level but not having the desired flexibility_
- [general] community is not big but bearable, ~2,500 downloads/week for @accounts/server is minimal but community in GH issues seems to be active
- [minor] GH README lists 33 contributors which is true while only 1 (and a bot) are active; this is normal for smaller repos but the listing of 33 faces at the end of README creates a notion of a popular repo which might be misleading

So, I stop here, IDK, I spent already too much time and couldn't get this working. Also is my code base littered with accounts snippets, nothing bad, just a preference thing: if I use an abstraction I like it to be less granular than my own code. Maybe the ded accounts server woluld have been the better choice but don't have time to setup this up as well and I prefer to have the accounts stuff merged with my current scheme and my app is not on a needs-to-be-a-microservices-architecture level yet.

I still like the idea despite my feedback, I'd love to use accounts, maybe I give accounts another try tmr but not sure :/

 ps: if I got anything wrong and/or didn't get the docs rights, a premature apology for reporting potentially wrong deficiencies, I am just an avg user who has limited time and wants to get stuff done.

**Comment by pradel** [comment] 2020-04-07 17:15
@desmap thanks for the detailed feedback, that's great and will help us to improve the repo!

As a side note, I am maintaining accounts-js during my free time aside from my full time job so the time I can spend on it is pretty limited, it's open-source so any help is welcome to improve the docs :)

Also, you might want to check the tutorial I wrote to [setup an apollo server with accounts-js](https://www.leopradel.com/blog/email-and-password-authentication-with-accounts-js-and-apollo-part-1). I need to include it in the docs.

> [minor] Docs inconsistent (GH README vs site), eg. Getting Started section merge vs graphql-tools helpers
[minor] GH README buggy code, eg. mergeGraphQLModules not declared (guess it should have been ...Schema)
[minor] GH README examples lack setting up the db
[minor] Mongo docs example lacks second arg for new AccountsServer (TS says services)

Yeah the README is really outdated now, the preferred way to create a graphql server is not with accounts-boost anymore, will need to be updated 👍.

> [major] despite having an own db connection to Mongo with useUnifiedTopology: true, Mongo complains that it's not there and Mongo reports about a failed connect => why does accounts tries to connect itself to Mongo? And if, it's ok but then it should do it in a proper way, hint: useUnifiedTopology (this has some aftertaste on the repo, Mongo introduced this this ages go), and it should be stated somewhere in the docs what accounts is doing

This looks like a bug to me, the `@accounts/mongo` package do not try to connect to the db the error (which is a warning and not an error) might come from another package you are using, if you have a reproducible example that would be great.

> [minor but infuriating] Docs actually don't tell how to let use your Mongo connection; setting up Mongo is described in the respective chapter but nowhere how to get the stuff into the server

Good point 👍 

> [minor but infuriating] Docs state that @apollo/boost is for the standalone server but then it's imported in the existing-server example; guess there must be a reason but for the reader it's just another question mark

Good point 👍 

> [ux/general/major] setup and API is very granular/scattered, good bc modular and probably flexible (I assume that's actually not flexible because of lacking Apollo Fed support) but also tedious bc there are many modules to be imported and most of the time I am in the docs trying to follow some guide but not actual thinking myself what to do

You are right you need to install multiple packages and setup the parts together, I am in the process of writing a detailed guide that will I hope remove this confusion.

> [ux/general/major] when merging with an existing scheme, would't Apollo Federation be the right choice? Apollo Fed provides a tighter integration with your existing scheme than just a simple merge => my first impression was here that accounts is such a modular API thriving for flexibility but the actual core isn't flexible, so I end up with a low abstraction level but not having the desired flexibility

Well Apollo Federation is great. The problem is that it does not follow the GraphQL specification. The current accounts-js graphql package is working with apollo but also with graphql-js. So either we can make it work with both apollo federation and graphql-js or we need another accounts-js package that would add support for apollo federation servers only. I didn't really dig into apollo federation so I don't have an answer for this one.

> [minor] GH README lists 33 contributors which is true while only 1 (and a bot) are active; this is normal for smaller repos but the listing of 33 faces at the end of README creates a notion of a popular repo which might be misleading

This part show all the people that contributed to the project, not just the active once, it's as a way to say thanks to everyone that is contributing to the repo :). This is really common in a lot of open source projects, for example, you can check https://github.com/all-contributors/all-contributors.

The project is not yet finished for a 1.0 version as the docs are really lacking. But the code itself is production-ready and is used by companies that have tens of thousands of users.

Thanks for the feedback, I hope you will give it another try and I really recommend that you take a look at the tutorial I linked at the top :)

Cheers

**Comment by pradel** [comment] 2020-04-15 09:47
Closing the issue for now, feel free to answer or reopen it if you think it should stay open.

**Closed by pradel** 2020-04-15 09:47 UTC
Labels: discussion
