### ISSUE TITLE
Duplicate export '__esModule' @accounts/graphql-client/lib/index.js

### ISSUE THREAD

**Issue by stolinski** [accounts-js/accounts#1061] opened 2020-10-19 19:13 UTC
# Bug report

## Describe the bug

I'm using Snowpack to load via modules rather than bundle and am hitting this error. Of which I've posted about in the discussion over there. https://github.com/snowpackjs/snowpack/discussions/1312

I'm wondering if it has to do with the exports in this file
https://github.com/accounts-js/accounts/blob/master/packages/graphql-client/src/index.ts

ie the 

`export { default as AccountsGraphQLClient, default } from './graphql-client';`

I'm note exactly sure what's going on with here but it seems like default is being exported both as AccountsGraphqlClient as well as default? Is that required? I'm also not sure if this is in fact the error, but it seems possible. I should note that @accounts/graphql-client is the only package that has an issue loading, so I doubt it's a problem with Snowpack specifically but probably something that needs tweaking in this module. 

Thoughts?

## To Reproduce

clone https://github.com/stolinski/snowpack-accounts-reproduction

`npm install`

`npm start`

## Expected behavior

Should just load the basic starting create react app like screen. Instead hitting an error in load.

## System information

`"@accounts/graphql-client": "^0.29.0",`

**Comment by pradel** [comment] 2021-02-01 09:42
@stolinski as what we are doing is actually valid and properly handled by webpack, the issue is really likely on snowpack side :)
Closing this one, feel free to reopen if you think the issue is on accounts-js side.

**Closed by pradel** 2021-02-01 09:42 UTC
Labels: bug
