### ISSUE TITLE
Failed authentication in client-password package

### ISSUE THREAD

**Issue by orinokai** [accounts-js/accounts#649] opened 2019-04-12 15:27 UTC
I'm trying to use the client-password package to authenticate with my accounts-js server. However, the `login` function hashes the password before sending it:

https://github.com/accounts-js/accounts/blob/master/packages/client-password/src/client-password.ts#L30

This function is essentially a wrapper around `client.loginWithService`, which itself just calls the 'authenticate' mutation, which expects a plain text password, and so authentication fails. Is there something I'm missing?

**Comment by derblitz** [comment] 2019-04-15 10:45
Can you post your code here?
Do you use user/password authentication (or email/password)?
Have you had a look at the two client examples in the examples folder of the repository (the REST and graphQL example)?

I've started using it last week and username/password authentication works (email / password (without user) seems to be buggy currently).
I use the following client code in order to authenticate (via a graphQl accounts-js server):
```
        try {
            await accountsPassword.login({
                user: {
                    username: this.state.email,
                },
                password: this.state.password,
            }).then(() => {
                this.props.push('/dashboard/');
            })
        } catch (err) {
            this.setState({ error: err.message });
        }
```

**Comment by orinokai** [comment] 2019-04-17 09:50
Thanks @derblitz. I'm importing the code from [examples/react-graphql-typescript/src/utils/accounts.ts](https://github.com/accounts-js/accounts/blob/abb3b43a4702ba4ca8b9128ce586d2ec114f918c/examples/react-graphql-typescript/src/utils/accounts.ts) and then running the following code, which gives me an exception with the message, "GraphQL error: Invalid credentials":

```js
accountsPassword.login({
  user: {
    username: 'test'
  },
  password: 'test123'
});
```

However, it works fine if I don't hash the password before sending, by changing [this line in client-password.ts](https://github.com/accounts-js/accounts/blob/abb3b43a4702ba4ca8b9128ce586d2ec114f918c/packages/client-password/src/client-password.ts#L33) to:

```js
password: user.password
```

So it seems that the client-password package is sending a hashed password, but the accounts-js server is expecting a plain-text password, which makes sense because I can authenticate successfully using the GraphQL playground without hashing the password.

My server is initialised with the accounts-boost package using the defaults. I've looked through the accounts-boost and server code but can't see any option that might instruct the `authenticate` mutation to accept a hashed password.

Very grateful for any advice on this.

**Comment by derblitz** [comment] 2019-04-17 20:08
I usually would say that I think the issue is in the server part, but let me ask the following first:

Do you use Mongo?, if yes, please check if the password is stored hashed or not hashed in the database. In Mongo accounts-js seems to create 2 collections (1 for users and 1 for sessions). In the users collection you should see the password (hashed of course).
 
The reason why I ask that is because I assume the error does not happen during the login, but instead, during signup (createUser function on the client).

Therefore, is it possible that you also changed the client code of the register function in the client (removed the hash)? If so, the behavior you're facing would make sense.

Please make sure you use the original client code, not one that was changed by you (maybe reinstall using yarn/npm or so).

Just an assumption - so please check the password in the database.

FYI, my signup code looks like this:
```
        try {
            await accountsPassword.createUser({
                email: this.state.email,
                username: this.state.email,
                password: this.state.password,
                profile: {
                    firstName: this.state.firstName,
                    lastName: this.state.lastName,
                },
            }).then(() => {
                accountsPassword.login({
                    user: {
                        username: this.state.email,
                    },
                    password: this.state.password,
                }).then(() => {
                    this.props.push('/dashboard/');
                })
            })
        } catch (err) {
            this.setState({ error: err.message });
        }
```

**Comment by orinokai** [comment] 2019-04-18 13:40
Great, you're right, I've just realised what's going on. The [login](https://github.com/accounts-js/accounts/blob/abb3b43a4702ba4ca8b9128ce586d2ec114f918c/packages/client-password/src/client-password.ts#L29) method in the client-password package expects the password to be SHA256 hashed. This is fine when the user has been created with the [createUser](https://github.com/accounts-js/accounts/blob/abb3b43a4702ba4ca8b9128ce586d2ec114f918c/packages/client-password/src/client-password.ts#L21) method in the package, because it creates the user with a hashed password, but I have been creating test users directly with the GraphQL playground using an unhashed password. Seems obvious now! Thanks for your help.

**Comment by derblitz** [comment] 2019-04-18 17:57
Ok great, then please close the issue.

**Closed** 2019-04-20 18:46 UTC
